/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function initApp(dataDir?: string | undefined | null): void
export declare function cmdAuthSetup(password: string): Promise<void>
export declare function cmdAuthUnlock(password: string): Promise<void>
export declare function cmdAuthLock(): void
export declare function cmdAuthStatus(): AuthStatus
export declare function cmdUpdateSettings(autoLockMinutes: number): void
export interface AuthStatus {
  isSetup: boolean
  unlocked: boolean
  autoLockMinutes: number
}
export declare function cmdGeneratePassword(): any
